/**
 * Real, downloadable outputs.
 *
 * The OpenSSL configuration is generated from the keys actually observed, so the
 * recommended groups and sizes follow the measurement rather than a generic
 * template. The runbook states the deadline arithmetic so a reader can audit it.
 */

import {
  DISCLAIMER,
  ENGINE_NAME,
  ENGINE_VERSION,
  MIGRATION_LEAD_YEARS,
  PQC_PARAMETERS,
  SHOR_ANCHOR,
} from "./engine/constants";
import { VQC_CIRCUITS, VQC_WEIGHTS } from "./engine/vqc";
import { SITE } from "../config/site";
import type { KeyObservation, Watch } from "./types";

export interface ExportBundle {
  openssl: string;
  runbook: string;
  dossier: Record<string, unknown>;
}

function isoDay(value: string): string {
  return value.slice(0, 10);
}

export function buildOpenSslConfig(
  watch: Watch,
  observations: KeyObservation[],
): string {
  const exposed = observations.filter((o) => o.engine.verdict !== "quantum_viable");
  const rsa = observations.find((o) => o.key.algorithm === "rsa");
  const mlkem = PQC_PARAMETERS.find((p) => p.label === "ML-KEM-768")!;
  const mldsa = PQC_PARAMETERS.find((p) => p.label === "ML-DSA-65")!;

  const groups = [
    "X25519MLKEM768:secp256r1mlkem768:secp384r1mlkemp1024",
    "X25519:secp256r1:secp384r1",
    "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",
  ].join(":");

  const lines = [
    "# Shorwatch generated OpenSSL 3.5 configuration",
    `# watch: ${watch.label || watch.host} (${watch.host})`,
    `# generated by ${ENGINE_NAME} ${ENGINE_VERSION}`,
    "#",
    "# This file is a starting point for a migration review, not a drop-in",
    "# deployment. Verify it against your own certificate authority, client",
    "# inventory and change-management process before use.",
    "",
    "openssl_conf = openssl_init",
    "",
    "[openssl_init]",
    "providers = provider_sectigo",
    "ssl_conf = ssl_sectigo",
    "",
    "[provider_sectigo]",
    "default = default_sectigo",
    "",
    "[ssl_sectigo]",
    "system_default = system_default_sectigo",
    "",
    "[default_sectigo]",
    "activate = 1",
    "",
    "## Key agreement groups, hybrid post-quantum first so a classical peer still",
    "## negotiates and a quantum-capable peer gets ML-KEM in the same handshake.",
    `ssl_conf_groups = ${groups}`,
    "",
    "## Signature algorithms for certificate signing, ML-DSA first with ECDSA",
    "## retained for clients that cannot yet chain-verify ML-DSA.",
    "signature_algorithms = mldsa65:ecdsa_secp256r1_sha256:mldsa44:ecdsa_secp384r1_sha384",
    "",
    "## Protocols. TLS 1.0/1.1 are removed deliberately.",
    "MinProtocol = TLSv1.2",
    "CipherString = DEFAULT:@SECLEVEL=1",
    "",
    "# --- measured facts this configuration responds to ---",
    `# observed algorithm: ${rsa ? rsa.key.parameterLabel ?? rsa.key.algorithm : "no RSA key observed"}`,
    `# observed modulus:   ${rsa?.key.bits ?? "n/a"} bits`,
    `# quantum deadline:  ${rsa ? isoDay(rsa.engine.crqDate) : "beyond model window"}`,
    `# keys requiring action: ${exposed.length} of ${observations.length}`,
    `# ML-KEM-768 public key / ciphertext: ${mlkem.publicKeyBytes} / ${mlkem.ciphertextBytes} bytes (${mlkem.standard}, level ${mlkem.nistLevel})`,
    `# ML-DSA-65 public key / signature:  ${mldsa.publicKeyBytes} / ${mldsa.signatureBytes} bytes (${mldsa.standard}, level ${mldsa.nistLevel})`,
    "",
  ];

  return lines.join("\n");
}

export function buildRunbook(watch: Watch, observations: KeyObservation[]): string {
  const lines: string[] = [];
  lines.push(`# Post-quantum migration runbook: ${watch.host}`);
  lines.push("");
  lines.push(`Generated by ${SITE.name} (${ENGINE_NAME} ${ENGINE_VERSION}).`);
  lines.push(`Confidentiality requirement: ${watch.retentionYears} year(s) from today.`);
  lines.push("");
  lines.push("## What was measured");
  lines.push("");
  if (observations.length === 0) {
    lines.push(
      "No key observation is stored for this watch yet. Run a live probe before acting on this document.",
    );
    lines.push("");
  }

  for (const observation of observations) {
    lines.push(`### ${observation.key.parameterLabel ?? observation.key.algorithm}`);
    lines.push("");
    lines.push(`- SubjectPublicKeyInfo SHA-256: \`${observation.spkiSha256}\``);
    lines.push(`- Certificate SHA-256: \`${observation.certificateSha256}\``);
    lines.push(`- Issuer: ${observation.issuerCommonName}`);
    lines.push(
      `- Valid: ${isoDay(observation.notBefore)} to ${isoDay(observation.notAfter)}`,
    );
    lines.push(`- Source: ${observation.source.label} (${observation.source.status})`);
    if (observation.transparency) {
      lines.push(
        `- Public in Certificate Transparency since: ${isoDay(observation.transparency.firstSeen)}`,
      );
      lines.push(`- CT issuance records returned: ${observation.transparency.issuanceCount}`);
    }
    lines.push("");
    lines.push("Scoring:");
    lines.push("");
    for (const factor of observation.engine.factors) {
      lines.push(
        `- **${factor.label}** — weight ${factor.weight}, raw ${factor.raw}, contribution ${factor.contribution}: ${factor.detail}`,
      );
    }
    lines.push("");
    lines.push(
      `- Verdict: ${observation.engine.verdict} (score ${observation.engine.score})`,
    );
    lines.push(`- Projected quantum deadline: ${observation.engine.crqDate}`);
    lines.push(
      `- Days until that deadline: ${Number.isFinite(observation.engine.daysToCrq) ? observation.engine.daysToCrq : "beyond window"}`,
    );
    lines.push(
      `- Resource model: ${observation.engine.quantum.logicalQubitsNeeded.toLocaleString("en-US")} logical qubits, ${observation.engine.quantum.physicalQubitsNeeded.toLocaleString("en-US")} physical qubits`,
    );
    lines.push(
      `- Quantum advisor (${VQC_CIRCUITS}): <Z0>=${observation.engine.advisor.expectationZ}, <Z0Z1>=${observation.engine.advisor.expectationZZ}, adjustment ${observation.engine.advisor.adjustment} points`,
    );
    lines.push(`- Engine seal: \`${observation.engine.seal}\``);
    lines.push("");
    lines.push(`**Action:** ${observation.engine.recommendation}`);
    lines.push("");
  }

  lines.push("## Ordered plan");
  lines.push("");
  const ordered = [...observations].sort(
    (a, b) => a.engine.daysToCrq - b.engine.daysToCrq || b.engine.score - a.engine.score,
  );
  ordered.forEach((observation, index) => {
    lines.push(
      `${index + 1}. \`${observation.key.parameterLabel ?? observation.key.algorithm}\` — migrate within ${Math.max(0, observation.engine.leadTimeDays)} days of lead time (deadline ${observation.engine.crqDate}).`,
    );
  });
  lines.push("");
  lines.push("## Assumptions behind the deadlines");
  lines.push("");
  lines.push(
    `- Resource anchor: ${SHOR_ANCHOR.citation} — ${SHOR_ANCHOR.logicalQubits} logical qubits, ~${SHOR_ANCHOR.physicalQubits.toLocaleString("en-US")} physical qubits for RSA-${SHOR_ANCHOR.modulusBits}.`,
  );
  lines.push(`- Migration lead time reserved: ${MIGRATION_LEAD_YEARS} years.`);
  lines.push(
    `- Quantum advisor weights: z=${VQC_WEIGHTS.z}, zz=${VQC_WEIGHTS.zz}, bias=${VQC_WEIGHTS.bias}.`,
  );
  lines.push("");
  lines.push("## Disclaimer");
  lines.push("");
  lines.push(DISCLAIMER);
  lines.push("");
  return lines.join("\n");
}

export function buildDossier(
  watch: Watch,
  observations: KeyObservation[],
  provenance: Array<{ sourceId: string; label: string; url: string; status: string; fetchedAt: string }>,
): Record<string, unknown> {
  return {
    product: SITE.name,
    engine: { name: ENGINE_NAME, version: ENGINE_VERSION },
    generatedAt: new Date().toISOString(),
    repository: SITE.repoUrl,
    watch: {
      id: watch.id,
      host: watch.host,
      label: watch.label,
      decision: watch.decision,
      retentionYears: watch.retentionYears,
      machine: watch.machine,
      live: watch.live,
      lastProbedAt: watch.lastProbedAt,
      notes: watch.notes,
    },
    observations: observations.map((observation) => ({
      spkiSha256: observation.spkiSha256,
      certificateSha256: observation.certificateSha256,
      key: observation.key,
      issuer: observation.issuerCommonName,
      validFrom: observation.notBefore,
      validTo: observation.notAfter,
      protocol: observation.protocol,
      cipher: observation.cipher,
      transparencyFirstSeen: observation.transparency?.firstSeen ?? null,
      engine: observation.engine,
    })),
    provenance,
    disclaimer: DISCLAIMER,
  };
}

export function buildBundle(
  watch: Watch,
  observations: KeyObservation[],
  provenance: Array<{ sourceId: string; label: string; url: string; status: string; fetchedAt: string }>,
): ExportBundle {
  return {
    openssl: buildOpenSslConfig(watch, observations),
    runbook: buildRunbook(watch, observations),
    dossier: buildDossier(watch, observations, provenance),
  };
}